### PR TITLE
Multiple files and additional options

### PR DESCRIPTION
**Pull request by fjenquin**
Allow multiple files as args
Allow directories as args
Added extension, fieldDelimiter and merge options

Ensured that no breaking changes are introduced. Same behavior if nothing changed in the parameters.

### CODE REVIEW

**Comment by fjenquin** [comment]
@othree could you please check and merge this PR if you are ok with it.

We do need those 2 "improvements" in order to be able to to use this.
- FieldDelimiter is a must in order to be able to open the files in Excel and have file easily shareable with our business.
- Multiple files allow us to have a common file translation file shared between different projects which also add their own translation file.

**Comment by fjenquin** [comment]
Just added 2 additional options (readEncoding and writeEncoding) in order to be able to manage different encodings.

Our source csv files are managed in excel and thus in latin1 encoding. The readEncoding was thus a must.
Output was already done in utf8 as we needed it but it was really easy to add option for adapting the write encoding too. So I have also done it.

README adapted to document those new options.

**Comment by fjenquin** [comment]
Replaced usage of object-path by creating manually the object and merging it.

I got errors when converting following file to json. It created an array with a lot of empty entries. Didn't find any in the file explaining it and tried to update object-path version but still same issue.

Here is the file that cause errors.
[errors.txt](https://github.com/othree/i18ncsv2json/files/1272547/errors.txt)

Managed to find a way to get this working easily with lodash merge and pure javascript.

**Comment by othree** [comment]
Hi

Thanks for your PR.
And sorry I am very busy recently.
So replied so late.

I think it will be better if you can separate the two changes into two PR.

1. Multiple file support
2. object-path part

Because the object-path part is a broken change.
It will need more discussion.

**Comment by fjenquin** [comment]
I have already created 2 first pull request that are for sure non breaking for the field delimiter and encodings adaptations which were 2 really simple fixes that cannot cause any regression in current behavior.

I'll still create 2 other separated pull request for multiple file support and object path replacement.

**Comment by othree** [comment]
Hi, thanks for the new PRs.
I have merged it into the repo.
I think multi-file will be ok too.

**Comment by fjenquin** [comment]
Modifications included in other pull requests. Closing this one.

**Pull request closed without merging**
